### ISSUE TITLE
If taxonomy module is disabled > crash

### ISSUE THREAD

**Issue by spoit** [wieni/wmcontroller#12]
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Drupal\wmcontroller\Routing\InjectFrontControllerRouteSubscriber::alterRoute() must be an instance of Symfony\Component\Routing\Route, null given, called in /vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php on line 63 and defined in /vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php:74
Stack trace:
#0 /vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php(63): Drupal\wmcontroller\Routing\InjectFrontControllerRouteSubscriber->alterRoute(NULL, 'term')
#1 /vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php(40): Drupal\wmcontroller\Routing\InjectFrontControllerRouteSubscriber->alterTaxonomyRoutes(Object(Symfony\Component\Routing\RouteCollection))
#2 /vagrant/www-mskgent-be/web/public/core/lib/Drupal/Core/Routing/Route in /vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php on line 74
Drush command terminated abnormally due to an unrecoverable error.                                                                               [error]
Error: Uncaught TypeError: Argument 1 passed to Drupal\wmcontroller\Routing\InjectFrontControllerRouteSubscriber::alterRoute() must be an
instance of Symfony\Component\Routing\Route, null given, called in
/vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php on line 63 and defined in
/vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php:74
Stack trace:
#0 /vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php(63):
Drupal\wmcontroller\Routing\InjectFrontControllerRouteSubscriber->alterRoute(NULL, 'term')
#1 /vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php(40):
Drupal\wmcontroller\Routing\InjectFrontControllerRouteSubscriber->alterTaxonomyRoutes(Object(Symfony\Component\Routing\RouteCollection))
#2 /vagrant/www-mskgent-be/web/public/core/lib/Drupal/Core/Routing/Route in
/vagrant/www-mskgent-be/web/public/modules/contrib/wmcontroller/src/Routing/InjectFrontControllerRouteSubscriber.php, line 74`

**Comment by frizinak** [comment]
Fixed in #15
