### ISSUE TITLE
Hijack rendering

### ISSUE THREAD

**Issue by frizinak** [wieni/wmcontroller#24]
Skip page.twig / html.twig, if a frontender wants to extend custom_html.twig he should be able to.

also removes the need for those retarded addHtmlHeadTag calls, frontender decides what goes into the head of the page.

**Comment by RobinHoutevelts** [comment]
For the View, Edit, ... actions:

`\Drupal\Core\Menu\Plugin\Block\LocalTasksBlock::build`
