### ISSUE TITLE
Clean up module

### ISSUE THREAD

**Issue by DieterHolvoet** [wieni/wmcontroller#45]
## General stuff
- [x] Cleanup code using `wieni/wmcodestyle`
- [x] Normalise composer.json
- [x] Add LICENSE in case it's missing. Also add the license to composer.json.
- [x] Add CHANGELOG.md (and UPGRADING.md, if applicable)
- [x] Add issue & pull request templates
- [x] Update repo description & tags
- [x] Update README
- [x] Update .gitignore
- [x] Check dependencies: ensure composer.json has a php & drupal/core version requirements and add missing requirements to the .info file 
- [x] Clean up branches (check SourceGraph for usages across projects)

## Code to check for relevance
- [x] cdnless.patch
- [x] pager stuff:
    - wmcontroller_preprocess_pager
    - wmcontroller_theme_registry_alter
    - Drupal\wmcontroller\EventSubscriber\PagerRewriteSubscriber
- [x] `ViewBuilder::createOriginalRenderArrayFromEntity`
   - [x] `setHeadElements`
   - [x] `addHeadElement`
   - [x] `setHooks`
   - [x] `getHooks`
   - [x] `addHeadElementsToRenderArray`
   - [x] `addCustomHooksToRenderArray`

**Comment by RobinHoutevelts** [comment]
>  cdnless.patch
 - [ ] I'll check which projects use this. I think it's good to delete this
