### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by frizinak** [wieni/wmcontroller#7]
- Skip drupal cache.
- Add middleware / event listener to handle cached responses.
- Use the dispatched EntityPresentedEvent to assemble a list of `cache tags`
- Cache the resulting html.
- Invalidate on entity_save

to drupalCacheInterface or not to drupalCacheInterface?

custom:

wm_cache:

| route | lang | html | expiry |
|-------|------|------|--------|

wm_cache_tags:

| route | lang | tag |
|-------|------|-----|

(route includes args. i.e: node/5 not node.canonical obviously)
 
custom: no alternate database backend (e.g.: redis)

drupal cache: huge serialized arrays, global locking (no go IMO)

`expiry` would be a config setting like so:
```yaml
wmcontroller.cache_config:
    max-age:
        node/\d+: 3600
        products/[^/]+/info: 300
        .*: 7200
```

and overridable in your controller.

**Comment by frizinak** [comment]
route should prolly be the actual request path.

we could disable `wm_cache.html` if the site is proxied by a cdn and still be able to purge based on tags using the wm_cache_tags.route column without having to lookup aliases (at least 2 purge requests instead of 1).

But this will lead to unnecessary duplicate entries if wm_cache.html is enabled.

**Comment by frizinak** [comment]
We're still missing a lot, only cache html? Store http headers aswell.
Storing languange probably wont work since we want handle cached responses as fast as possible.

**Comment by frizinak** [comment]
basic impl in #8 

what remains: 

- schema
- cron task to purge expired pages
- handle default drupal tag purges OR implement own hook_entity_update. 
- allow adding custom tags from controller (e.g: product_overview, config:5)


unrelated to server-side caching: we should also add wmcontroller.cache.config.maxage for client side caching, adding this manually in each controller is tiresome.

**Comment by frizinak** [comment]
wmcontroller.cache.config.expiry is lacking in 2 ways:

- matches on actual paths, so no-go atm (aliases)
- we need more granular config: entity type and bundle for example, this will require a setEntity call in every controller.

2) will also help the totally unrelated issue of metatags and the likes.
Adding a mainEntity variable (set through setEntity) would allow  us to add metatags and other generic infomation to the root template (if we start using twig's extends / blocks).

**Comment by RobinHoutevelts** [comment]
> we need more granular config: entity type and bundle for example, this will require a setEntity call in every controller.

Except for `node.canonical` routes where we already know which entity will be shown.

**Comment by frizinak** [comment]
Most of it is implemented

what remains:

- entity specific rules (instead of useless path regexes, or in addition to)
- listening for the tag purge event (actual purging is implemented)

bugs:

- Request headers that modify the response (e.g.: Accept, Accept-Encoding, ...)

**Comment by frizinak** [comment]
entity specific rules and fix duplicate header bug (core bug imo)

**Comment by frizinak** [comment]
as far as I can see there is no 'tag invalidation' event / hook, all invocations of invalidateTags are done directly from e.g.: Save methods on the injected CacheTagsInvalidatorInterface.

hook_entity_save then?

**Comment by frizinak** [comment]
implemented using hook_entity_update.
